version: '3.9'

services:
  currency_postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_alerter
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
