"""Add active and key name to api keys

Revision ID: 55ffca1e0a7f
Revises: ae2d9cf17b67
Create Date: 2023-10-16 13:01:07.736474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ffca1e0a7f'
down_revision: Union[str, None] = 'ae2d9cf17b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column(
        'is_active', sa.Boolean(), nullable=True))
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=True))
    op.execute('UPDATE api_keys SET is_active = true')
    op.execute("UPDATE api_keys SET name = 'My Key'")
    op.alter_column('api_keys', 'is_active', nullable=False)
    op.alter_column('api_keys', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'name')
    op.drop_column('api_keys', 'is_active')
    # ### end Alembic commands ###
