"""add obfuscated key column

Revision ID: 74f933e4557e
Revises: a1e2774556bf
Create Date: 2023-10-15 17:37:53.322459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f933e4557e'
down_revision: Union[str, None] = 'a1e2774556bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('obfuscated_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'obfuscated_key')
    # ### end Alembic commands ###
